sudo: required
language: python
python:
    - "3.5"
install:
    - pip install codecov
    - pip install pytest-cov
    - pip install pytest-qt
    - pip install sip
    - pip install pyqt5

script:
    - py.test --cov=./

after_success:
    - codecov
